spring:
  application:
    name: security-api
  datasource:
    url: jdbc:postgresql://localhost:5433/security
    username: shreesha
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        type: TRACE
        generate_statistics: true
        format_sql: true

server:
  port: 8081

logging:
  file:
    name: logs/application.log
  level:
    org:
      springframework:
        security: TRACE
        data:
          jpa:
            repository:
              query: TRACE
      hibernate:
        SQL: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    root: INFO
