version: "3.9"
services:
  postgres_security:
    image: postgres:latest
    container_name: postgressecuritydb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: security
      POSTGRES_USER: shreesha
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_security_data:/var/lib/postgresql/security/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: shreesha@shreesha.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    depends_on:
      - postgres_security

volumes:
  postgres_security_data: